[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pump_fun = "9e7FCcemFyvPUrXgUfxKCZvNVpLiiYMo34t77Kwa241u"

[programs.devnet]
pump_fun = "9e7FCcemFyvPUrXgUfxKCZvNVpLiiYMo34t77Kwa241u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
